baseURL = "https://tienldn.site"
theme = 'cozy-garden'
languageCode = "en-US"
assetDir='assets'
title = "Nhat Tien"
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
buildFuture = true

[params]
  favicon = "/favicon.ico"
  dateFormat = "Jan 02, 2006"
  logo = "/images/blue-mouse.webp"
  description = "personal blog of Nhat Tien"
  [params.header]
    menu = [
      { label = "About", href = "/about" },
      { label = "Thoughts", href = "/thoughts" },
      { label = "Tags", href = "/tag" },
      { label = "Archive", href = "/blog" }
    ]
  [params.footer]
    github = "https://github.com/nhat-tien"
    linkedin = "https://www.linkedin.com/in/ledntien"
    rss = "/index.xml"
  [params.twtxt]
    nick = "nhat-tien"
    url = "https://tienldn.site/twtxt.txt"
    description = "tien's thoughts" 

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[permalinks]
  blog = "/blog/:contentbasename/"
  tags = "/tag/:slug"
  [permalinks.section]
    blog = '/blog/'

[outputs]
  home = [ "HTML", "RSS", "JSON", "TWTXT" ]

[outputFormats.TWTXT]
  mediaType = "text/plain"
  baseName = "twtxt"
  isPlainText = true
  notAlternative = true
