baseURL = "https://tienldn.site"
theme = 'cozy-garden'
languageCode = "en-US"
assetDir='assets'
title = "Nhat Tien"
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
buildFuture = true

[params]
  favicon = "/favicon.ico"
  dateFormat = "02/01/2006"
  logo = "/images/blue-mouse.webp"
  description = "personal blog of Nhat Tien"
  [params.footer]
    github = "https://github.com/nhat-tien"
    linkedin = "https://www.linkedin.com/in/ledntien"
    rss = "/index.xml"

[markup]
  [markup.highlight]
    # lineNos = true
    noClasses = false
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[permalinks]
  blog = "/blogs/:contentbasename/"
  tags = "/tags/:slug"
  [permalinks.section]
    blog = '/blogs/'

[outputs]
  home = ["HTML", "RSS", "JSON"]
