baseURL = "https://tienldn.site"
theme = 'cozy-garden'
languageCode = "en-US"
assetDir='assets'
description = "personal blog of Nhat Tien"

title = "Nhat Tien"

enableRobotsTXT = true
enableEmoji = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  favicon = "/images/favicon.png"
  dateFormat = "02-01-2006"


[markup]
  [markup.highlight]
    # lineNos = true
    noClasses = false
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[permalinks]
  blog = "/blogs/:slug/"
  tags = "/tags/:slug"
  [permalinks.section]
    blog = '/blogs/'

[outputs]
  home = ["HTML", "RSS", "JSON"]
