baseURL = "https://tienldn.site"
theme = 'cozy-garden'
languageCode = "en-US"
assetDir='assets'
title = "Nhat Tien"
enableRobotsTXT = true
enableEmoji = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
buildFuture = true

[params]
  favicon = "/favicon.ico"
  dateFormat = "Jan 02, 2006"
  logo = "/images/blue-mouse.webp"
  description = "personal blog of Nhat Tien"
  math = false 
  [params.header]
    menu = [
      { label = "About", href = "/about" },
      { label = "Thoughts", href = "/thoughts" },
      { label = "Tags", href = "/tag" },
      { label = "Blog", href = "/blog" }
    ]
  [params.footer]
    github = "https://github.com/nhat-tien"
    linkedin = "https://www.linkedin.com/in/ledntien"
    rss = "/index.xml"
    twtxt = "/twtxt.txt"
    starThisRepoUrl = "https://github.com/nhat-tien/blog"
    highlights = [
      { label = "Map Of Content", href = "/blog/map-of-content/" },
      { label = "My Awesome List", href = "/blog/my-awesome-list/" }
    ]
    nav = [
      { label = "About", href = "/about" },
      { label = "Thoughts", href = "/thoughts" },
      { label = "Now", href = "/blog/now" },
      { label = "Tags", href = "/tag" },
      { label = "Archive", href = "/blog" }
    ]
  [params.twtxt]
    nick = "nhat-tien"
    name = "Nhat Tien"
    url = "https://tienldn.site/twtxt.txt"
    description = "tien's thoughts"
    avatar = "https://tienldn.site/images/blue-mouse.webp"

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false
    lineNumbersInTable = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[permalinks]
  blog = "/blog/:contentbasename/"
  tags = "/tag/:slug"
  [permalinks.section]
    blog = '/blog/'

[outputs]
  home = [ "HTML", "RSS", "JSON", "TWTXT" ]

[outputFormats.TWTXT]
  mediaType = "text/plain"
  baseName = "twtxt"
  isPlainText = true
  notAlternative = true
